import type {
  CardAbility,
  CardAttack,
  EnergyType,
  RoleTag,
  Supertype,
  TcgCard,
  TcgSet,
} from "../types";

const LEGAL = { standard: "Legal" } as const;

/** pokemontcg.io set ids used in image URLs */
export const SET_IMAGE_IDS: Record<string, string> = {
  TEF: "sv5",
  TWM: "sv6",
  SFA: "sv6pt5",
  SCR: "sv7",
  SSP: "sv8",
  PRE: "sv8pt5",
  JTG: "sv9",
  DRI: "sv10",
  BLK: "blk",
  WHT: "wht",
  MEG: "me1",
  PFL: "me2",
  ASC: "me3",
  POR: "me4",
  SVP: "svp",
  MEP: "mep",
};

type CardInput = {
  setCode: string;
  setName: string;
  number: string;
  name: string;
  regulationMark: string;
  supertype: Supertype;
  subtypes: string[];
  hp?: number;
  types?: EnergyType[];
  evolvesFrom?: string;
  attacks?: CardAttack[];
  abilities?: CardAbility[];
  weaknesses?: { type: EnergyType; value: string }[];
  resistances?: { type: EnergyType; value: string }[];
  retreat?: number;
  rules?: string[];
  rarity?: string;
  roles?: RoleTag[];
  whenGood?: string;
  whenBrick?: string;
  scripted?: boolean;
};

function card(input: CardInput): TcgCard {
  const setId = SET_IMAGE_IDS[input.setCode] ?? input.setCode.toLowerCase();
  const id = `${input.setCode.toLowerCase()}-${input.number}`;
  return {
    id,
    name: input.name,
    setCode: input.setCode,
    setName: input.setName,
    number: input.number,
    regulationMark: input.regulationMark,
    supertype: input.supertype,
    subtypes: input.subtypes,
    hp: input.hp,
    types: input.types,
    evolvesFrom: input.evolvesFrom,
    attacks: input.attacks,
    abilities: input.abilities,
    weaknesses: input.weaknesses,
    resistances: input.resistances,
    retreat: input.retreat,
    rules: input.rules,
    rarity: input.rarity,
    imageSmall: `https://images.pokemontcg.io/${setId}/${String(parseInt(input.number, 10) || input.number)}.png`,
    imageLarge: `https://images.pokemontcg.io/${setId}/${String(parseInt(input.number, 10) || input.number)}_hires.png`,
    ptcgoCode: input.setCode,
    legalities: { ...LEGAL },
    roles: input.roles,
    whenGood: input.whenGood,
    whenBrick: input.whenBrick,
    scripted: input.scripted,
  };
}

function basicEnergy(
  setCode: string,
  setName: string,
  number: string,
  type: EnergyType,
  mark: string,
): TcgCard {
  return card({
    setCode,
    setName,
    number,
    name: `${type} Energy`,
    regulationMark: mark,
    supertype: "Energy",
    subtypes: ["Basic"],
    types: [type],
    rules: [`Provides 1 ${type} Energy.`],
    rarity: "Common",
    roles: ["engine"],
    whenGood: "Fuels attackers of this type.",
    whenBrick: "Dead if you are off-type or flooded.",
    scripted: true,
  });
}

function item(
  setCode: string,
  setName: string,
  number: string,
  name: string,
  mark: string,
  rules: string,
  extra: Partial<CardInput> = {},
): TcgCard {
  return card({
    setCode,
    setName,
    number,
    name,
    regulationMark: mark,
    supertype: "Trainer",
    subtypes: ["Item"],
    rules: [rules],
    rarity: "Common",
    ...extra,
  });
}

function supporter(
  setCode: string,
  setName: string,
  number: string,
  name: string,
  mark: string,
  rules: string,
  extra: Partial<CardInput> = {},
): TcgCard {
  return card({
    setCode,
    setName,
    number,
    name,
    regulationMark: mark,
    supertype: "Trainer",
    subtypes: ["Supporter"],
    rules: [rules],
    rarity: "Uncommon",
    ...extra,
  });
}

function stadium(
  setCode: string,
  setName: string,
  number: string,
  name: string,
  mark: string,
  rules: string,
  extra: Partial<CardInput> = {},
): TcgCard {
  return card({
    setCode,
    setName,
    number,
    name,
    regulationMark: mark,
    supertype: "Trainer",
    subtypes: ["Stadium"],
    rules: [rules],
    rarity: "Uncommon",
    ...extra,
  });
}

function aceSpec(
  setCode: string,
  setName: string,
  number: string,
  name: string,
  mark: string,
  rules: string,
  subtype: "Item" | "Supporter" | "Stadium" | "Tool" = "Item",
  extra: Partial<CardInput> = {},
): TcgCard {
  return card({
    setCode,
    setName,
    number,
    name,
    regulationMark: mark,
    supertype: "Trainer",
    subtypes: [subtype, "ACE SPEC"],
    rules: ["You can't have more than 1 ACE SPEC card in your deck.", rules],
    rarity: "ACE SPEC Rare",
    roles: ["ace-spec", ...(extra.roles ?? [])],
    scripted: true,
    ...extra,
  });
}

const TEF = "Temporal Forces";
const TWM = "Twilight Masquerade";
const SFA = "Shrouded Fable";
const SCR = "Stellar Crown";
const SSP = "Surging Sparks";
const PRE = "Prismatic Evolutions";
const JTG = "Journey Together";
const DRI = "Destined Rivals";
const BLK = "Black Bolt";
const WHT = "White Flare";
const MEG = "Mega Evolution";
const PFL = "Phantasmal Flames";
const ASC = "Ascended Heroes";
const POR = "Perfect Order";
const SVP = "SV Black Star Promos";
const MEP = "ME Black Star Promos";

export const CARDS: TcgCard[] = [
  // ─── Format staples (scripted) ───────────────────────────────────────────
  item("SSP", SSP, "196", "Ultra Ball", "H", "Discard 2 cards, then search your deck for a Pokémon and put it into your hand.", {
    roles: ["search", "engine"],
    whenGood: "Core consistency for every Evolution deck.",
    whenBrick: "Costs two discards — painful when hand is thin.",
    scripted: true,
    rarity: "Uncommon",
  }),
  item("PFL", PFL, "068", "Nest Ball", "J", "Search your deck for a Basic Pokémon and put it onto your Bench.", {
    roles: ["search", "starter"],
    whenGood: "Sets up Bench early without discarding.",
    whenBrick: "Bricks mid/late when Bench is full or Basics are gone.",
    scripted: true,
  }),
  item("TWM", TWM, "144", "Buddy-Buddy Poffin", "H", "Search your deck for up to 2 Basic Pokémon with 70 HP or less and put them onto your Bench.", {
    roles: ["search", "starter", "engine"],
    whenGood: "Best early Bench loader for 70 HP Basics.",
    whenBrick: "Dead if no low-HP Basics left or Bench is full.",
    scripted: true,
  }),
  item("SSP", SSP, "191", "Rare Candy", "H", "Evolve a Basic into a Stage 2, skipping Stage 1 (ignoring evolution timing).", {
    roles: ["engine", "search"],
    whenGood: "Turns on Stage 2 attackers one turn earlier.",
    whenBrick: "Dead without matching Basic + Stage 2 in hand.",
    scripted: true,
  }),
  supporter("PRE", PRE, "132", "Boss's Orders", "H", "Switch in 1 of your opponent's Benched Pokémon to the Active Spot.", {
    roles: ["gust", "disruption"],
    whenGood: "Prize mapping and KO sequencing.",
    whenBrick: "Wasted without a KO follow-up or when Bench is empty.",
    scripted: true,
    rarity: "Rare",
  }),
  item("SCR", SCR, "160", "Counter Catcher", "H", "If you have more Prize cards remaining than your opponent, switch in 1 of their Benched Pokémon.", {
    roles: ["gust", "tech"],
    whenGood: "Comeback gust when behind on prizes.",
    whenBrick: "Illegal / blank when ahead or tied on prizes.",
    scripted: true,
  }),
  supporter("SSP", SSP, "185", "Iono", "H", "Each player shuffles their hand into their deck and draws cards equal to prizes remaining.", {
    roles: ["draw", "disruption"],
    whenGood: "Refills your hand and wrecks theirs mid-game.",
    whenBrick: "Can refill an opponent who was bricked.",
    scripted: true,
  }),
  supporter("PRE", PRE, "133", "Professor's Research", "H", "Discard your hand, then draw 7 cards.", {
    roles: ["draw", "engine"],
    whenGood: "Raw redraw when the hand is disposable.",
    whenBrick: "Discards key pieces you still needed.",
    scripted: true,
  }),
  supporter("SSP", SSP, "169", "Arven", "H", "Search your deck for an Item and a Pokémon Tool and put them into your hand.", {
    roles: ["search", "engine"],
    whenGood: "Fetches ACE SPEC / Tool + consistency Item in one supporter.",
    whenBrick: "Soft if you need draw more than tutor.",
    scripted: true,
  }),
  supporter("SCR", SCR, "133", "Crispin", "H", "Search your deck for a Basic Energy and a Basic Energy of a different type; attach one and put the other into your hand.", {
    roles: ["engine", "search"],
    whenGood: "Dual-type ramp for Dragapult / multi-energy attackers.",
    whenBrick: "Blank if you only run one Energy type.",
    scripted: true,
  }),
  item("SFA", SFA, "061", "Night Stretcher", "H", "Put a Pokémon or Basic Energy from your discard pile into your hand.", {
    roles: ["search", "engine"],
    whenGood: "Recovers discarded attackers and Energy.",
    whenBrick: "Dead if discard is empty of targets.",
    scripted: true,
  }),
  item("TEF", TEF, "163", "Earthen Vessel", "H", "Discard a card from your hand. Search your deck for up to 2 Basic Energy and put them into your hand.", {
    roles: ["search", "engine"],
    whenGood: "Fast Energy tutor after a discard.",
    whenBrick: "Needs a discardable card in hand.",
    scripted: true,
  }),
  item("PRE", PRE, "138", "Super Rod", "H", "Shuffle up to 3 in any combination of Pokémon and Basic Energy from your discard pile into your deck.", {
    roles: ["engine", "heal"],
    whenGood: "Recycles prized/discarded resources for long games.",
    whenBrick: "Slow when you need immediate hand cards.",
    scripted: true,
  }),
  item("SSP", SSP, "194", "Switch", "H", "Switch your Active Pokémon with 1 of your Benched Pokémon.", {
    roles: ["tech"],
    whenGood: "Retreat without paying Energy; pivots into attackers.",
    whenBrick: "Dead with empty Bench.",
    scripted: true,
  }),
  item("SSP", SSP, "186", "Pokégear 3.0", "H", "Look at the top 7 cards of your deck; you may take a Supporter into your hand.", {
    roles: ["search", "engine"],
    whenGood: "Finds Boss/Iono/Research on curve.",
    whenBrick: "Misses if Supporters are deep or already in hand.",
    scripted: true,
  }),
  item("SSP", SSP, "187", "Poké Ball", "H", "Flip a coin. If heads, search your deck for a Pokémon and put it into your hand.", {
    roles: ["search"],
    whenGood: "Budget Pokémon search when Ultra Ball density is low.",
    whenBrick: "50% miss rate — unreliable.",
    scripted: true,
  }),
  item("SSP", SSP, "172", "Energy Switch", "H", "Move a Basic Energy from 1 of your Pokémon to another of your Pokémon.", {
    roles: ["engine", "tech"],
    whenGood: "Repositions Energy after KOs or onto a fresh attacker.",
    whenBrick: "Dead without Energy on board.",
    scripted: true,
  }),
  item("SSP", SSP, "170", "Crushing Hammer", "H", "Flip a coin. If heads, discard an Energy from your opponent's Active Pokémon.", {
    roles: ["disruption", "tech"],
    whenGood: "Slows single-Energy attackers and Tools-on-Energy lines.",
    whenBrick: "Coin-flip Item — often a brick.",
    scripted: true,
  }),
  aceSpec(
    "SFA",
    SFA,
    "062",
    "Unfair Stamp",
    "H",
    "Your opponent shuffles their hand into their deck and draws 2 cards. During your opponent's next turn, they can't play Item cards.",
    "Item",
    {
      roles: ["ace-spec", "disruption"],
      whenGood: "Locks Item-heavy decks after a decisive KO turn.",
      whenBrick: "Soft vs decks that do not lean on Items.",
    },
  ),
  aceSpec(
    "TWM",
    TWM,
    "163",
    "Secret Box",
    "H",
    "Discard 3 cards. Search your deck for an Item, a Supporter, a Stadium, and a Tool; put them into your hand.",
    "Item",
    {
      roles: ["ace-spec", "search", "engine"],
      whenGood: "One-card toolbox grab for combo turns.",
      whenBrick: "Costs 3 discards — catastrophic on thin hands.",
    },
  ),

  // ─── Fezandipiti / Munkidori ─────────────────────────────────────────────
  card({
    setCode: "SFA",
    setName: SFA,
    number: "038",
    name: "Fezandipiti ex",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex"],
    hp: 210,
    types: ["Psychic"],
    retreat: 1,
    weaknesses: [{ type: "Metal", value: "×2" }],
    abilities: [
      {
        name: "Adrena-Brain",
        type: "Ability",
        text: "Once during your turn, if this Pokémon has any damage counters on it, you may draw cards until you have 3 cards in your hand.",
      },
    ],
    attacks: [
      {
        name: "Cruel Arrow",
        cost: ["Psychic", "Colorless", "Colorless"],
        damage: "100",
        text: "This attack does 100 damage to 1 of your opponent's Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["draw", "engine", "attacker"],
    whenGood: "Format draw engine once damaged; snipes Bench.",
    whenBrick: "Needs damage on itself and Psychic Energy for attack.",
    scripted: true,
  }),
  card({
    setCode: "SFA",
    setName: SFA,
    number: "072",
    name: "Munkidori",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 110,
    types: ["Psychic"],
    retreat: 1,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    abilities: [
      {
        name: "Adrena-Brain",
        type: "Ability",
        text: "Once during your turn, if this Pokémon has any damage counters on it, you may move up to 3 damage counters from 1 of your Pokémon to 1 of your opponent's Pokémon.",
      },
    ],
    attacks: [
      {
        name: "Mind Bend",
        cost: ["Psychic", "Colorless"],
        damage: "60",
        text: "Your opponent's Active Pokémon is now Confused.",
      },
    ],
    rarity: "Uncommon",
    roles: ["tech", "engine"],
    whenGood: "Moves chip damage onto KO ranges for Dragapult lines.",
    whenBrick: "Needs damage on itself and setup space.",
    scripted: true,
  }),

  // ─── Dragapult ex line (TWM) ─────────────────────────────────────────────
  card({
    setCode: "TWM",
    setName: TWM,
    number: "128",
    name: "Dreepy",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Psychic"],
    retreat: 1,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    attacks: [
      {
        name: "Bite",
        cost: ["Psychic"],
        damage: "10",
      },
    ],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Poffin target into Dragapult.",
    whenBrick: "Dead late without Rare Candy / Stage pieces.",
  }),
  card({
    setCode: "TWM",
    setName: TWM,
    number: "129",
    name: "Drakloak",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 90,
    types: ["Psychic"],
    evolvesFrom: "Dreepy",
    retreat: 1,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    abilities: [
      {
        name: "Recon Directive",
        type: "Ability",
        text: "Once during your turn, you may look at the top 2 cards of your deck and put 1 into your hand. Put the other on the bottom of your deck.",
      },
    ],
    attacks: [
      {
        name: "Spooky Shot",
        cost: ["Psychic", "Colorless"],
        damage: "40",
      },
    ],
    rarity: "Common",
    roles: ["engine"],
    whenGood: "Filter draw while climbing into Dragapult.",
    whenBrick: "Often skipped with Rare Candy.",
  }),
  card({
    setCode: "TWM",
    setName: TWM,
    number: "130",
    name: "Dragapult ex",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Stage 2", "ex"],
    hp: 320,
    types: ["Psychic"],
    evolvesFrom: "Drakloak",
    retreat: 1,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    attacks: [
      {
        name: "Jet Headbutt",
        cost: ["Colorless"],
        damage: "70",
      },
      {
        name: "Phantom Dive",
        cost: ["Psychic", "Psychic"],
        damage: "200",
        text: "Put 6 damage counters on your opponent's Active Pokémon. Then put damage counters equal to the remaining damage of this attack on your opponent's Benched Pokémon in any way you like. (Apply Weakness and Resistance for Active; Bench placement ignores W/R.)",
        prizes: 2,
      },
    ],
    rules: [
      "Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards.",
      "Variants: straight Psychic build; Dusknoir ability partners; Blaziken ex Fire splash.",
    ],
    rarity: "Double Rare",
    roles: ["attacker", "engine"],
    whenGood: "Spread-then-snipe with Boss/Counter Catcher closes games.",
    whenBrick: "Loses to faster single-prize pressure and rough Psychic techs.",
  }),

  // ─── Festival Lead package ───────────────────────────────────────────────
  card({
    setCode: "TWM",
    setName: TWM,
    number: "018",
    name: "Dipplin",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 80,
    types: ["Grass"],
    evolvesFrom: "Applin",
    retreat: 2,
    weaknesses: [{ type: "Fire", value: "×2" }],
    abilities: [
      {
        name: "Festival Lead",
        type: "Ability",
        text: "Attacks used by your Pokémon that have the Festival Lead Ability cost Colorless less for each Festival Grounds in play (including opponent's).",
      },
    ],
    attacks: [
      {
        name: "Do the Wave",
        cost: ["Grass", "Colorless"],
        damage: "20+",
        text: "This attack does 20 more damage for each of your Benched Pokémon.",
      },
    ],
    rarity: "Uncommon",
    roles: ["engine", "attacker"],
    whenGood: "Enables Festival Grounds loop with Thwackey/Seaking.",
    whenBrick: "Needs Stadium lock and Applin setup.",
  }),
  card({
    setCode: "TWM",
    setName: TWM,
    number: "017",
    name: "Applin",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 40,
    types: ["Grass"],
    retreat: 1,
    weaknesses: [{ type: "Fire", value: "×2" }],
    attacks: [{ name: "Rollout", cost: ["Grass"], damage: "10" }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Into Dipplin for Festival Lead.",
    whenBrick: "Tiny HP — easy KO before evolution.",
  }),
  card({
    setCode: "TWM",
    setName: TWM,
    number: "015",
    name: "Thwackey",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 100,
    types: ["Grass"],
    evolvesFrom: "Grookey",
    retreat: 2,
    weaknesses: [{ type: "Fire", value: "×2" }],
    abilities: [
      {
        name: "Festival Lead",
        type: "Ability",
        text: "Attacks used by your Pokémon that have the Festival Lead Ability cost Colorless less for each Festival Grounds in play.",
      },
    ],
    attacks: [
      {
        name: "Drum Beating",
        cost: ["Grass", "Colorless"],
        damage: "50",
        text: "During your opponent's next turn, the Defending Pokémon can't retreat.",
      },
    ],
    rarity: "Uncommon",
    roles: ["engine", "attacker"],
    whenGood: "Second Festival Lead body for Stadium loop.",
    whenBrick: "Needs Grookey and Stadium.",
  }),
  card({
    setCode: "TWM",
    setName: TWM,
    number: "014",
    name: "Grookey",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Grass"],
    retreat: 1,
    weaknesses: [{ type: "Fire", value: "×2" }],
    attacks: [{ name: "Scratch", cost: ["Grass"], damage: "10" }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Poffinable into Thwackey.",
    whenBrick: "Without evolution it's a weak Basic.",
  }),
  card({
    setCode: "SCR",
    setName: SCR,
    number: "028",
    name: "Seaking",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 110,
    types: ["Water"],
    evolvesFrom: "Goldeen",
    retreat: 1,
    weaknesses: [{ type: "Lightning", value: "×2" }],
    abilities: [
      {
        name: "Festival Lead",
        type: "Ability",
        text: "Attacks used by your Pokémon that have the Festival Lead Ability cost Colorless less for each Festival Grounds in play.",
      },
    ],
    attacks: [
      {
        name: "Festival Style",
        cost: ["Colorless", "Colorless"],
        damage: "30+",
        text: "If Festival Grounds is in play, this attack does 90 more damage and heal 30 damage from this Pokémon.",
      },
    ],
    rarity: "Uncommon",
    roles: ["attacker", "engine"],
    whenGood: "Stadium-on payoff attacker for Festival Lead.",
    whenBrick: "Blank without Festival Grounds.",
  }),
  card({
    setCode: "SCR",
    setName: SCR,
    number: "027",
    name: "Goldeen",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Water"],
    retreat: 1,
    weaknesses: [{ type: "Lightning", value: "×2" }],
    attacks: [{ name: "Flip Turn", cost: ["Colorless"], damage: "10", text: "You may switch this Pokémon with 1 of your Benched Pokémon." }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Into Seaking for Festival.",
    whenBrick: "Low impact alone.",
  }),
  stadium(
    "TEF",
    TEF,
    "149",
    "Festival Grounds",
    "H",
    "Each Pokémon that has the Festival Lead Ability (both yours and your opponent's) has no Retreat Cost and takes 30 less damage from attacks from the opponent's Pokémon.",
    {
      roles: ["engine"],
      whenGood: "Turns on Festival Lead cost reduction and bulk.",
      whenBrick: "Shared — opponent Festival pieces also benefit.",
    },
  ),
  supporter("TWM", TWM, "152", "Lacey", "H", "Shuffle your hand into your deck. Draw 4 cards. If your opponent has 3 or fewer Prize cards remaining, draw 8 cards instead.", {
    roles: ["draw"],
    whenGood: "Late-game Festival / combo redraw.",
    whenBrick: "Weak early when prizes are high.",
  }),

  // ─── Dusknoir line + Blaziken (Dragapult partners) ───────────────────────
  card({
    setCode: "SFA",
    setName: SFA,
    number: "019",
    name: "Duskull",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 60,
    types: ["Psychic"],
    retreat: 1,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    attacks: [{ name: "Will-O-Wisp", cost: ["Psychic"], damage: "20" }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Into Dusknoir for Cursed Blast KO help.",
    whenBrick: "Dead draw without Stage 2 package.",
  }),
  card({
    setCode: "SFA",
    setName: SFA,
    number: "020",
    name: "Dusclops",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 90,
    types: ["Psychic"],
    evolvesFrom: "Duskull",
    retreat: 2,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    attacks: [{ name: "Psychic Sphere", cost: ["Psychic", "Colorless"], damage: "50" }],
    rarity: "Common",
    roles: ["engine"],
    whenGood: "Bridge into Dusknoir.",
    whenBrick: "Often Candied past.",
  }),
  card({
    setCode: "SFA",
    setName: SFA,
    number: "021",
    name: "Dusknoir",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Stage 2"],
    hp: 160,
    types: ["Psychic"],
    evolvesFrom: "Dusclops",
    retreat: 3,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    abilities: [
      {
        name: "Cursed Blast",
        type: "Ability",
        text: "Once during your turn, you may put 13 damage counters on 1 of your opponent's Pokémon. If you use this Ability, this Pokémon is Knocked Out.",
      },
    ],
    attacks: [
      {
        name: "Shadow Bind",
        cost: ["Psychic", "Psychic", "Colorless"],
        damage: "150",
        text: "During your opponent's next turn, the Defending Pokémon can't retreat.",
      },
    ],
    rarity: "Rare",
    roles: ["tech", "attacker"],
    whenGood: "Sacrificial KO enabler with Dragapult spread.",
    whenBrick: "Self-KO costs a prize — timing matters.",
  }),
  card({
    setCode: "JTG",
    setName: JTG,
    number: "024",
    name: "Torchic",
    regulationMark: "I",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Fire"],
    retreat: 1,
    weaknesses: [{ type: "Water", value: "×2" }],
    attacks: [{ name: "Ember", cost: ["Fire"], damage: "20" }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Into Blaziken ex Fire partner package.",
    whenBrick: "Off-type in pure Psychic Dragapult.",
  }),
  card({
    setCode: "JTG",
    setName: JTG,
    number: "025",
    name: "Combusken",
    regulationMark: "I",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 90,
    types: ["Fire"],
    evolvesFrom: "Torchic",
    retreat: 1,
    weaknesses: [{ type: "Water", value: "×2" }],
    attacks: [{ name: "Double Kick", cost: ["Fire", "Colorless"], damage: "40" }],
    rarity: "Common",
    roles: ["engine"],
    whenGood: "Bridge to Blaziken ex.",
    whenBrick: "Skipped with Rare Candy.",
  }),
  card({
    setCode: "JTG",
    setName: JTG,
    number: "026",
    name: "Blaziken ex",
    regulationMark: "I",
    supertype: "Pokémon",
    subtypes: ["Stage 2", "ex"],
    hp: 320,
    types: ["Fire"],
    evolvesFrom: "Combusken",
    retreat: 2,
    weaknesses: [{ type: "Water", value: "×2" }],
    abilities: [
      {
        name: "Scorching Feather",
        type: "Ability",
        text: "Once during your turn, you may discard a Fire Energy from this Pokémon. If you do, put 6 damage counters on 1 of your opponent's Benched Pokémon.",
      },
    ],
    attacks: [
      {
        name: "Flame Storm",
        cost: ["Fire", "Fire", "Colorless"],
        damage: "200",
        text: "Discard a Fire Energy from this Pokémon. Heal 30 damage from each of your Benched Pokémon.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker", "tech"],
    whenGood: "Bench pressure partner for Dragapult variants.",
    whenBrick: "Needs Fire Energy and Candy; prized Torchic hurts.",
  }),

  // ─── Mega Excadrill ex line ──────────────────────────────────────────────
  card({
    setCode: "MEG",
    setName: MEG,
    number: "048",
    name: "Drilbur",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Fighting"],
    retreat: 2,
    weaknesses: [{ type: "Grass", value: "×2" }],
    attacks: [{ name: "Mud-Slap", cost: ["Fighting"], damage: "20" }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Into Mega Excadrill ex.",
    whenBrick: "High retreat for a Basic.",
  }),
  card({
    setCode: "MEG",
    setName: MEG,
    number: "049",
    name: "Excadrill",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 120,
    types: ["Fighting"],
    evolvesFrom: "Drilbur",
    retreat: 2,
    weaknesses: [{ type: "Grass", value: "×2" }],
    attacks: [{ name: "Drill Run", cost: ["Fighting", "Colorless"], damage: "80" }],
    rarity: "Uncommon",
    roles: ["attacker"],
    whenGood: "Bridge / backup before Mega Evolution.",
    whenBrick: "Outclassed once Mega Excadrill is online.",
  }),
  card({
    setCode: "MEG",
    setName: MEG,
    number: "050",
    name: "Mega Excadrill ex",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Stage 1", "ex", "Mega"],
    hp: 340,
    types: ["Fighting"],
    evolvesFrom: "Excadrill",
    retreat: 3,
    weaknesses: [{ type: "Grass", value: "×2" }],
    attacks: [
      {
        name: "Earthquake Drill",
        cost: ["Fighting", "Fighting", "Colorless"],
        damage: "280",
        text: "This attack also does 20 damage to each of your Benched Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)",
        prizes: 2,
      },
      {
        name: "Iron Tunneler",
        cost: ["Fighting", "Colorless"],
        damage: "120",
        text: "Discard an Energy from your opponent's Active Pokémon.",
        prizes: 2,
      },
    ],
    rules: [
      "Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards.",
      "Mega Evolution rule: When you play this Pokémon from your hand to evolve Excadrill, you may attach up to 3 Basic Fighting Energy from your discard pile to this Pokémon.",
    ],
    rarity: "Double Rare",
    roles: ["attacker"],
    whenGood: "High HP tank that closes 2-prizes cleanly.",
    whenBrick: "Self-Bench damage and Grass Weakness.",
  }),

  // ─── N's Zoroark ex line ─────────────────────────────────────────────────
  card({
    setCode: "DRI",
    setName: DRI,
    number: "098",
    name: "N's Zorua",
    regulationMark: "I",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Darkness"],
    retreat: 1,
    weaknesses: [{ type: "Grass", value: "×2" }],
    attacks: [{ name: "Stampede", cost: ["Darkness"], damage: "20" }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "N's lineage into Zoroark ex.",
    whenBrick: "Needs N's Zoroark specifically.",
  }),
  card({
    setCode: "DRI",
    setName: DRI,
    number: "099",
    name: "N's Zoroark ex",
    regulationMark: "I",
    supertype: "Pokémon",
    subtypes: ["Stage 1", "ex"],
    hp: 280,
    types: ["Darkness"],
    evolvesFrom: "N's Zorua",
    retreat: 2,
    weaknesses: [{ type: "Grass", value: "×2" }],
    abilities: [
      {
        name: "Trade",
        type: "Ability",
        text: "You must discard a card from your hand in order to use this Ability. Once during your turn, you may draw 2 cards.",
      },
    ],
    attacks: [
      {
        name: "Night Torment",
        cost: ["Darkness", "Darkness", "Colorless"],
        damage: "160",
        text: "Your opponent reveals their hand. Discard a card you find there.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker", "draw", "engine", "disruption"],
    whenGood: "Trade engine plus hand disruption closer.",
    whenBrick: "Trade discards precious pieces; Grass Weakness.",
  }),
  supporter("DRI", DRI, "158", "N's Plan", "I", "Look at the top 3 cards of your deck. Put them into your hand or shuffle them into your deck, then draw 3 cards.", {
    roles: ["draw", "engine"],
    whenGood: "Synergizes with N's Pokémon disruption plans.",
    whenBrick: "Competes with Iono/Research for supporter slot.",
  }),

  // ─── Clefairy box ────────────────────────────────────────────────────────
  card({
    setCode: "PFL",
    setName: PFL,
    number: "033",
    name: "Cleffa",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 30,
    types: ["Psychic"],
    retreat: 0,
    weaknesses: [{ type: "Metal", value: "×2" }],
    attacks: [
      {
        name: "Twinkle Draw",
        cost: [],
        text: "Draw until you have 4 cards in your hand.",
      },
    ],
    rarity: "Common",
    roles: ["draw", "starter"],
    whenGood: "Free retreat draw Baby for box shells.",
    whenBrick: "30 HP — dies to any chip.",
  }),
  card({
    setCode: "PFL",
    setName: PFL,
    number: "034",
    name: "Clefairy",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Psychic"],
    retreat: 1,
    weaknesses: [{ type: "Metal", value: "×2" }],
    abilities: [
      {
        name: "Moonlight Box",
        type: "Ability",
        text: "Once during your turn, you may search your deck for a Basic Pokémon that isn't a Baby Pokémon and put it onto your Bench. Then, shuffle your deck.",
      },
    ],
    attacks: [
      {
        name: "Metronome",
        cost: ["Psychic", "Colorless"],
        text: "Choose 1 of your opponent's Active Pokémon's attacks and use it as this attack.",
      },
    ],
    rarity: "Uncommon",
    roles: ["engine", "starter", "tech"],
    whenGood: "Box enabler that tutors diverse Basics.",
    whenBrick: "Metronome needs a useful opposing attack.",
  }),
  card({
    setCode: "PFL",
    setName: PFL,
    number: "035",
    name: "Clefable ex",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Stage 1", "ex"],
    hp: 260,
    types: ["Psychic"],
    evolvesFrom: "Clefairy",
    retreat: 2,
    weaknesses: [{ type: "Metal", value: "×2" }],
    attacks: [
      {
        name: "Moon Impact",
        cost: ["Psychic", "Colorless"],
        damage: "120",
        prizes: 2,
      },
      {
        name: "Sparkle Box",
        cost: ["Psychic", "Psychic", "Colorless"],
        damage: "180",
        text: "You may put an Energy attached to this Pokémon into your hand. If you do, search your deck for a Stadium and put it into play.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker", "engine"],
    whenGood: "Flexible closer for Clefairy box shells.",
    whenBrick: "Metal Weakness and Stage 1 tempo.",
  }),

  // ─── Mega Gengar / Mega Charizard Y stubs ────────────────────────────────
  card({
    setCode: "MEG",
    setName: MEG,
    number: "061",
    name: "Gastly",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 50,
    types: ["Psychic"],
    retreat: 1,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    attacks: [{ name: "Astonish", cost: ["Psychic"], damage: "10" }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Into Mega Gengar ex.",
    whenBrick: "Fragile Basic.",
  }),
  card({
    setCode: "MEG",
    setName: MEG,
    number: "062",
    name: "Haunter",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 80,
    types: ["Psychic"],
    evolvesFrom: "Gastly",
    retreat: 1,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    attacks: [{ name: "Poison Gas", cost: ["Psychic"], damage: "30", text: "Your opponent's Active Pokémon is now Poisoned." }],
    rarity: "Common",
    roles: ["engine"],
    whenGood: "Bridge to Mega Gengar.",
    whenBrick: "Often Candied past.",
  }),
  card({
    setCode: "MEG",
    setName: MEG,
    number: "063",
    name: "Mega Gengar ex",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Stage 2", "ex", "Mega"],
    hp: 350,
    types: ["Psychic"],
    evolvesFrom: "Haunter",
    retreat: 2,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    abilities: [
      {
        name: "Shadow Gate",
        type: "Ability",
        text: "Once during your turn, if this Pokémon is in the Active Spot, you may switch it with 1 of your Benched Pokémon. If you do, put 3 damage counters on your opponent's Active Pokémon.",
      },
    ],
    attacks: [
      {
        name: "Nightmare Pressure",
        cost: ["Psychic", "Psychic", "Colorless"],
        damage: "220",
        text: "Your opponent's Active Pokémon is now Asleep. Put 3 damage counters on 1 of your opponent's Benched Pokémon.",
        prizes: 2,
      },
    ],
    rules: [
      "Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards.",
      "Mega Evolution rule: When you play this Pokémon from your hand to evolve Haunter, you may draw until you have 6 cards in your hand.",
    ],
    rarity: "Double Rare",
    roles: ["attacker", "disruption"],
    whenGood: "Pivot pressure plus sleep disruption.",
    whenBrick: "Stage 2 Mega ramp; Darkness Weakness.",
  }),
  card({
    setCode: "MEG",
    setName: MEG,
    number: "012",
    name: "Charmander",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Fire"],
    retreat: 1,
    weaknesses: [{ type: "Water", value: "×2" }],
    attacks: [{ name: "Ember", cost: ["Fire"], damage: "30", text: "Discard a Fire Energy from this Pokémon." }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Into Mega Charizard Y ex stub line.",
    whenBrick: "Self-discard on attack.",
  }),
  card({
    setCode: "MEG",
    setName: MEG,
    number: "013",
    name: "Charmeleon",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: 100,
    types: ["Fire"],
    evolvesFrom: "Charmander",
    retreat: 2,
    weaknesses: [{ type: "Water", value: "×2" }],
    attacks: [{ name: "Fire Fang", cost: ["Fire", "Colorless"], damage: "70" }],
    rarity: "Common",
    roles: ["engine"],
    whenGood: "Bridge to Mega Charizard Y.",
    whenBrick: "Candied past in dedicated builds.",
  }),
  card({
    setCode: "ASC",
    setName: ASC,
    number: "019",
    name: "Mega Charizard Y ex",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Stage 2", "ex", "Mega"],
    hp: 360,
    types: ["Fire"],
    evolvesFrom: "Charmeleon",
    retreat: 2,
    weaknesses: [{ type: "Water", value: "×2" }],
    attacks: [
      {
        name: "Inferno Wing",
        cost: ["Fire", "Fire", "Colorless"],
        damage: "250",
        text: "Discard 2 Fire Energy from this Pokémon. This attack does 50 damage to 1 of your opponent's Benched Pokémon.",
        prizes: 2,
      },
    ],
    rules: [
      "Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards.",
      "Stub: Ascended Heroes Mega Charizard Y for meta coverage.",
    ],
    rarity: "Double Rare",
    roles: ["attacker"],
    whenGood: "High ceiling Fire Mega attacker.",
    whenBrick: "Energy hungry; Water Weakness.",
  }),

  // ─── Other legal cards so every set has count > 0 ────────────────────────
  card({
    setCode: "TEF",
    setName: TEF,
    number: "060",
    name: "Iron Hands ex",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex"],
    hp: 230,
    types: ["Lightning"],
    retreat: 4,
    weaknesses: [{ type: "Fighting", value: "×2" }],
    attacks: [
      {
        name: "Arm Press",
        cost: ["Lightning", "Lightning", "Colorless"],
        damage: "160",
        prizes: 2,
      },
      {
        name: "Amp You Very Much",
        cost: ["Lightning", "Lightning", "Lightning", "Colorless"],
        damage: "120",
        text: "If your opponent's Pokémon is Knocked Out by damage from this attack, take 1 more Prize card.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker"],
    whenGood: "Prize-positive closer vs single-prize lines.",
    whenBrick: "High retreat; Fighting Weakness.",
  }),
  item("TEF", TEF, "145", "Heavy Baton", "H", "If the Pokémon this card is attached to has a Retreat Cost of 3 or more and is Knocked Out, move all Energy to 1 Benched Pokémon.", {
    subtypes: ["Pokémon Tool"],
    roles: ["tech"],
    whenGood: "Energy transfer on KO for tanky Basics.",
    whenBrick: "Blank on low-retreat attackers.",
  }),
  card({
    setCode: "SCR",
    setName: SCR,
    number: "087",
    name: "Terapagos ex",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex", "Tera"],
    hp: 230,
    types: ["Colorless"],
    retreat: 3,
    weaknesses: [{ type: "Fighting", value: "×2" }],
    attacks: [
      {
        name: "Unified Beatdown",
        cost: ["Colorless", "Colorless"],
        damage: "30×",
        text: "This attack does 30 damage for each of your Benched Pokémon that has an Ability.",
        prizes: 2,
      },
    ],
    rules: ["Tera rule / Pokémon ex rule apply."],
    rarity: "Double Rare",
    roles: ["attacker"],
    whenGood: "Ability-heavy Bench payoff.",
    whenBrick: "Needs populated Ability Bench.",
  }),
  card({
    setCode: "SSP",
    setName: SSP,
    number: "057",
    name: "Pikachu ex",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex"],
    hp: 200,
    types: ["Lightning"],
    retreat: 1,
    weaknesses: [{ type: "Fighting", value: "×2" }],
    attacks: [
      {
        name: "Friends 'Til the End",
        cost: ["Colorless", "Colorless"],
        damage: "30×",
        text: "This attack does 30 damage for each of your Benched Pokémon.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker"],
    whenGood: "Bench-count aggro.",
    whenBrick: "Falls off vs gust and spread.",
  }),
  card({
    setCode: "PRE",
    setName: PRE,
    number: "025",
    name: "Eevee",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 70,
    types: ["Colorless"],
    retreat: 1,
    weaknesses: [{ type: "Fighting", value: "×2" }],
    attacks: [{ name: "Tackle", cost: ["Colorless"], damage: "20" }],
    rarity: "Common",
    roles: ["starter"],
    whenGood: "Flexible evolution bridge in Prismatic shells.",
    whenBrick: "Without Eeveelutions it's filler.",
  }),
  card({
    setCode: "PRE",
    setName: PRE,
    number: "034",
    name: "Sylveon ex",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Stage 1", "ex"],
    hp: 270,
    types: ["Psychic"],
    evolvesFrom: "Eevee",
    retreat: 1,
    weaknesses: [{ type: "Metal", value: "×2" }],
    abilities: [
      {
        name: "Sympatha-Appeal",
        type: "Ability",
        text: "Once during your turn, you may attach a Basic Psychic Energy from your hand to 1 of your Benched Pokémon.",
      },
    ],
    attacks: [
      {
        name: "Magical Shot",
        cost: ["Psychic", "Colorless", "Colorless"],
        damage: "160",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["engine", "attacker"],
    whenGood: "Psychic attach support for Dragapult-adjacent shells.",
    whenBrick: "Competes for Bench and Energy.",
  }),
  card({
    setCode: "JTG",
    setName: JTG,
    number: "112",
    name: "Lillie's Clefairy ex",
    regulationMark: "I",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex"],
    hp: 190,
    types: ["Psychic"],
    retreat: 1,
    weaknesses: [{ type: "Metal", value: "×2" }],
    attacks: [
      {
        name: "Fairy Zone",
        cost: ["Psychic", "Colorless"],
        damage: "50+",
        text: "If your opponent's Active Pokémon is a Dragon Pokémon, this attack does 50 more damage.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker", "tech"],
    whenGood: "Dragon check and Lillie synergy.",
    whenBrick: "Narrow outside Dragon matchups.",
  }),
  supporter("JTG", JTG, "145", "Lillie", "I", "Draw cards until you have 6 cards in your hand.", {
    roles: ["draw"],
    whenGood: "Gentle early redraw.",
    whenBrick: "Weak when already at 6+ cards.",
  }),
  card({
    setCode: "DRI",
    setName: DRI,
    number: "045",
    name: "Team Rocket's Mewtwo ex",
    regulationMark: "I",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex"],
    hp: 240,
    types: ["Psychic"],
    retreat: 2,
    weaknesses: [{ type: "Darkness", value: "×2" }],
    resistances: [{ type: "Fighting", value: "-30" }],
    attacks: [
      {
        name: "Power Report",
        cost: ["Psychic", "Colorless"],
        damage: "30×",
        text: "This attack does 30 damage for each card in your opponent's hand.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker", "disruption"],
    whenGood: "Punishes fat hands after Iono fails.",
    whenBrick: "Soft vs thin hands.",
  }),
  card({
    setCode: "BLK",
    setName: BLK,
    number: "077",
    name: "Zekrom ex",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex"],
    hp: 230,
    types: ["Lightning"],
    retreat: 2,
    weaknesses: [{ type: "Fighting", value: "×2" }],
    attacks: [
      {
        name: "Bolt Strike",
        cost: ["Lightning", "Lightning", "Colorless"],
        damage: "200",
        text: "This Pokémon also does 30 damage to itself.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker"],
    whenGood: "Straightforward Lightning beatstick.",
    whenBrick: "Recoil plus Fighting Weakness.",
  }),
  item("BLK", BLK, "120", "Black Bolt Badge", "J", "Search your deck for a Lightning Energy and attach it to 1 of your Lightning Pokémon.", {
    roles: ["engine", "search"],
    whenGood: "Accelerates Zekrom lines.",
    whenBrick: "Dead off Lightning.",
  }),
  card({
    setCode: "WHT",
    setName: WHT,
    number: "078",
    name: "Reshiram ex",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex"],
    hp: 230,
    types: ["Fire"],
    retreat: 2,
    weaknesses: [{ type: "Water", value: "×2" }],
    attacks: [
      {
        name: "Blue Flare",
        cost: ["Fire", "Fire", "Colorless"],
        damage: "210",
        text: "Discard 2 Fire Energy from this Pokémon.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Double Rare",
    roles: ["attacker"],
    whenGood: "High damage Fire Basic.",
    whenBrick: "Energy discard tax; Water Weakness.",
  }),
  item("WHT", WHT, "121", "White Flare Badge", "J", "Search your deck for a Fire Energy and attach it to 1 of your Fire Pokémon.", {
    roles: ["engine", "search"],
    whenGood: "Fuels Reshiram / Charizard lines.",
    whenBrick: "Dead off Fire.",
  }),
  stadium("PFL", PFL, "090", "Phantom Arena", "J", "Whenever a Pokémon with a Mega Evolution rule is Knocked Out, its owner draws 2 cards.", {
    roles: ["engine", "tech"],
    whenGood: "Softens Mega KO losses.",
    whenBrick: "Helps both players.",
  }),
  card({
    setCode: "ASC",
    setName: ASC,
    number: "055",
    name: "Hero's Bond",
    regulationMark: "J",
    supertype: "Trainer",
    subtypes: ["Item"],
    rules: ["Search your deck for a Mega Evolution Pokémon and put it into your hand."],
    rarity: "Uncommon",
    roles: ["search"],
    whenGood: "Tutors Mega Charizard / Mega Gengar pieces.",
    whenBrick: "Dead without Mega Stage in deck.",
  }),
  card({
    setCode: "POR",
    setName: POR,
    number: "088",
    name: "Order Tablet",
    regulationMark: "J",
    supertype: "Trainer",
    subtypes: ["Item"],
    rules: ["Look at the top 5 cards of your deck. You may reveal a Stadium or ACE SPEC you find there and put it into your hand. Put the other cards back in any order."],
    rarity: "Uncommon",
    roles: ["search", "engine"],
    whenGood: "Finds Stadium/ACE SPEC without discarding.",
    whenBrick: "Misses if those cards are deep.",
  }),
  card({
    setCode: "POR",
    setName: POR,
    number: "041",
    name: "Perfect Order Rotom",
    regulationMark: "J",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: 80,
    types: ["Lightning"],
    retreat: 1,
    weaknesses: [{ type: "Fighting", value: "×2" }],
    abilities: [
      {
        name: "Catalog Scan",
        type: "Ability",
        text: "Once during your turn, you may look at the top card of your deck. If it is an Item card, you may put it into your hand.",
      },
    ],
    attacks: [{ name: "Static Shock", cost: ["Lightning"], damage: "30" }],
    rarity: "Uncommon",
    roles: ["engine", "tech"],
    whenGood: "Item filter for toolbox decks.",
    whenBrick: "Low HP Basic.",
  }),
  card({
    setCode: "SVP",
    setName: SVP,
    number: "148",
    name: "Pecharunt ex",
    regulationMark: "H",
    supertype: "Pokémon",
    subtypes: ["Basic", "ex"],
    hp: 190,
    types: ["Darkness"],
    retreat: 1,
    weaknesses: [{ type: "Fighting", value: "×2" }],
    abilities: [
      {
        name: "Subjugating Chains",
        type: "Ability",
        text: "Once during your turn, you may switch in 1 of your Benched Darkness Pokémon to the Active Spot. If you do, this Pokémon is Poisoned.",
      },
    ],
    attacks: [
      {
        name: "Irritated Outburst",
        cost: ["Darkness", "Darkness"],
        damage: "60×",
        text: "This attack does 60 damage for each Prize card your opponent has taken.",
        prizes: 2,
      },
    ],
    rules: ["Pokémon ex rule: When this Pokémon is Knocked Out, your opponent takes 2 Prize cards."],
    rarity: "Promo",
    roles: ["engine", "attacker"],
    whenGood: "Darkness pivot engine for Munkidori/N lines.",
    whenBrick: "Self-Poison and Fighting Weakness.",
  }),
  card({
    setCode: "MEP",
    setName: MEP,
    number: "001",
    name: "Mega Ring",
    regulationMark: "J",
    supertype: "Trainer",
    subtypes: ["Pokémon Tool"],
    rules: ["The Mega Evolution Pokémon this card is attached to takes 30 less damage from attacks."],
    rarity: "Promo",
    roles: ["tech", "heal"],
    whenGood: "Bulk for Mega Excadrill / Mega Gengar.",
    whenBrick: "Blank on non-Mega attackers.",
  }),
  stadium("SSP", SSP, "178", "Artazon", "H", "Once during each player's turn, that player may search their deck for a Basic Pokémon that doesn't have a Rule Box and put it onto their Bench.", {
    roles: ["engine", "search"],
    whenGood: "Shared Basic setup Stadium.",
    whenBrick: "Opponent also builds Bench.",
  }),
  item("SFA", SFA, "060", "PokéVital A", "H", "Heal 120 damage from 1 of your Pokémon. If you healed any damage this way, discard this Pokémon's attached Tool.", {
    roles: ["heal", "tech"],
    whenGood: "Big heal for damaged Fez / attackers.",
    whenBrick: "Forces Tool discard after heal.",
  }),
  supporter("SCR", SCR, "135", "Briar", "H", "You can use this card only if your opponent has exactly 2 Prize cards remaining. During this turn, if your opponent's Pokémon is Knocked Out by damage from your Pokémon's attacks, take 1 more Prize card.", {
    roles: ["tech"],
    whenGood: "Prize-positive endgame vs 2-prize board states.",
    whenBrick: "Timing-restricted supporter.",
  }),
  item("TEF", TEF, "146", "Maximum Belt", "H", "Attacks used by the Pokémon this card is attached to do 50 more damage to your opponent's Active Pokémon ex.", {
    subtypes: ["Pokémon Tool"],
    roles: ["tech"],
    whenGood: "Pushes OHKOs on opposing ex.",
    whenBrick: "Dead vs non-ex Active.",
  }),

  // ─── Basic Energy (scripted) ─────────────────────────────────────────────
  basicEnergy("SSP", SSP, "209", "Psychic", "H"),
  basicEnergy("SSP", SSP, "210", "Fire", "H"),
  basicEnergy("SSP", SSP, "211", "Grass", "H"),
  basicEnergy("SSP", SSP, "212", "Water", "H"),
  basicEnergy("SSP", SSP, "213", "Lightning", "H"),
  basicEnergy("SSP", SSP, "214", "Fighting", "H"),
  basicEnergy("SSP", SSP, "215", "Darkness", "H"),
  basicEnergy("SSP", SSP, "216", "Metal", "H"),
  basicEnergy("MEG", MEG, "100", "Psychic", "J"),
  basicEnergy("MEG", MEG, "101", "Fire", "J"),
  basicEnergy("MEG", MEG, "102", "Fighting", "J"),
];

const SET_META: Omit<TcgSet, "legalCardCount">[] = [
  {
    id: "sv5",
    code: "TEF",
    name: "Temporal Forces",
    series: "Scarlet & Violet",
    releaseDate: "2024-03-22",
    ptcgoCode: "TEF",
    marks: ["H"],
  },
  {
    id: "sv6",
    code: "TWM",
    name: "Twilight Masquerade",
    series: "Scarlet & Violet",
    releaseDate: "2024-05-24",
    ptcgoCode: "TWM",
    marks: ["H"],
  },
  {
    id: "sv6pt5",
    code: "SFA",
    name: "Shrouded Fable",
    series: "Scarlet & Violet",
    releaseDate: "2024-08-02",
    ptcgoCode: "SFA",
    marks: ["H"],
  },
  {
    id: "sv7",
    code: "SCR",
    name: "Stellar Crown",
    series: "Scarlet & Violet",
    releaseDate: "2024-09-13",
    ptcgoCode: "SCR",
    marks: ["H"],
  },
  {
    id: "sv8",
    code: "SSP",
    name: "Surging Sparks",
    series: "Scarlet & Violet",
    releaseDate: "2024-11-08",
    ptcgoCode: "SSP",
    marks: ["H"],
  },
  {
    id: "sv8pt5",
    code: "PRE",
    name: "Prismatic Evolutions",
    series: "Scarlet & Violet",
    releaseDate: "2025-01-17",
    ptcgoCode: "PRE",
    marks: ["H"],
  },
  {
    id: "sv9",
    code: "JTG",
    name: "Journey Together",
    series: "Scarlet & Violet",
    releaseDate: "2025-03-28",
    ptcgoCode: "JTG",
    marks: ["I"],
  },
  {
    id: "sv10",
    code: "DRI",
    name: "Destined Rivals",
    series: "Scarlet & Violet",
    releaseDate: "2025-05-30",
    ptcgoCode: "DRI",
    marks: ["I"],
  },
  {
    id: "blk",
    code: "BLK",
    name: "Black Bolt",
    series: "Scarlet & Violet",
    releaseDate: "2025-07-18",
    ptcgoCode: "BLK",
    marks: ["J"],
  },
  {
    id: "wht",
    code: "WHT",
    name: "White Flare",
    series: "Scarlet & Violet",
    releaseDate: "2025-07-18",
    ptcgoCode: "WHT",
    marks: ["J"],
  },
  {
    id: "me1",
    code: "MEG",
    name: "Mega Evolution",
    series: "Mega Evolution",
    releaseDate: "2025-09-26",
    ptcgoCode: "MEG",
    marks: ["J"],
  },
  {
    id: "me2",
    code: "PFL",
    name: "Phantasmal Flames",
    series: "Mega Evolution",
    releaseDate: "2025-11-14",
    ptcgoCode: "PFL",
    marks: ["J"],
  },
  {
    id: "me3",
    code: "ASC",
    name: "Ascended Heroes",
    series: "Mega Evolution",
    releaseDate: "2026-01-23",
    ptcgoCode: "ASC",
    marks: ["J"],
  },
  {
    id: "me4",
    code: "POR",
    name: "Perfect Order",
    series: "Mega Evolution",
    releaseDate: "2026-03-27",
    ptcgoCode: "POR",
    marks: ["J"],
  },
  {
    id: "svp",
    code: "SVP",
    name: "SV Black Star Promos",
    series: "Scarlet & Violet",
    releaseDate: "2023-03-31",
    ptcgoCode: "SVP",
    marks: ["H", "I"],
  },
  {
    id: "mep",
    code: "MEP",
    name: "ME Black Star Promos",
    series: "Mega Evolution",
    releaseDate: "2025-09-26",
    ptcgoCode: "MEP",
    marks: ["J"],
  },
];

export const SETS: TcgSet[] = SET_META.map((set) => ({
  ...set,
  legalCardCount: CARDS.filter((c) => c.setCode === set.code).length,
}));
